version: "3.3"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - WEB:/var/www/wordpress
    networks:
      - inception
    env_file:
      - ./.env
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - WEB:/var/www/wordpress
    networks:
      - inception
    env_file:
      - ./.env
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    env_file:
      - ./.env
    restart: unless-stopped

volumes:
  WEB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge

