services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - maria_password
      - maria_root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    environment:
      MARIA_HOST: mariadb:3306
      REDIS_HOST: redis:6379
    secrets:
      - redis_password
      - maria_password
      - wp_user_password
      - wp_root_password
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm7.4"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
      - adminer_data:/var/www/adminer
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
      portfolio:
        condition: service_healthy
      portainer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    build: ./requirements/bonus/redis/.
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - inception
    environment:
      REDIS_PASSWORD: /run/secrets/redis_password
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ftp:
    build: ./requirements/bonus/ftp/.
    container_name: ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    environment:
      WP_HOST: wordpress:9000
    secrets:
      - ftp_user_password
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "21"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    build: ./requirements/bonus/adminer/.
    container_name: adminer
    restart: unless-stopped
    volumes:
      - adminer_data:/var/www/adminer
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm7.4"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  portfolio:
    build: ./requirements/bonus/portfolio/.
    container_name: portfolio
    restart: unless-stopped
    volumes:
      - portfolio_data:/usr/src/app/
    networks:
      - inception
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  portainer:
    build: ./requirements/bonus/portainer/.
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    env_file:
      - .env
    environment:
      PT_USER_PASSWORD: /run/secrets/pt_user_password
    secrets:
      - pt_user_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/wordpress
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/redis
  portfolio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/portfolio
  adminer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/adminer
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/portainer

networks:
  inception:

secrets:
  maria_password:
    file: ../secrets/maria_password.txt
  maria_root_password:
    file: ../secrets/maria_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_root_password:
    file: ../secrets/wp_root_password.txt
  redis_password:
    file: ../secrets/redis_password.txt
  ftp_user_password:
    file: ../secrets/ftp_user_password.txt
  pt_user_password:
    file: ../secrets/pt_user_password.txt
