services:
  mariadb:
    build: ./requirements/mariadb/.
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - maria_password
      - maria_root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  wordpress:
    build: ./requirements/wordpress/.
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped
    environment:
      MARIA_HOST: mariadb:3306
      REDIS_HOST: redis:6379
    secrets:
      - redis_password
      - maria_password
      - wp_user_password
      - wp_admin_password
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    build: ./requirements/redis/.
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: /run/secrets/redis_password
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  ftp:
    build: ./requirements/ftp/.
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    environment:
      WP_HOST: wordpress:9000
    restart: unless-stopped
    secrets:
      - ftp_user_password
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "21"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/mariadb
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/redis

networks:
  inception:

secrets:
  maria_password:
    file: ../secrets/maria_password.txt
  maria_root_password:
    file: ../secrets/maria_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  redis_password:
    file: ../secrets/redis_password.txt
  ftp_user_password:
    file: ../secrets/ftp_user_password.txt
