version: "3.3"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - WP_HOST=mariadb:3306
      - MARIA_PASSWORD=/run/secrets/maria_password
      - WP_USER_PASSWORD=/run/secrets/wp_user_password
      - WP_ADMIN_PASSWORD=/run/secrets/wp_admin_password
    secrets:
      - maria_password
      - wp_user_password
      - wp_admin_password

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    environment:
      - MARIA_PASSWORD=/run/secrets/maria_password
      - MARIA_ROOT_PASSWORD=/run/secrets/maria_root_password
    secrets:
      - maria_password
      - maria_root_password

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/mariadb

networks:
  inception:
    driver: bridge

secrets:
  maria_password:
    file: ../secrets/maria_password.txt
  maria_root_password:
    file: ../secrets/maria_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt


