services:
  mariadb:
    build: ./requirements/mariadb/.
    image: requirements/mariadb
    deploy:
      restart_policy:
        condition: any
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    environment:
      WP_HOST: mariadb:3306
    secrets:
      - maria_password
      - maria_root_password

  wordpress:
    build: ./requirements/wordpress/.
    image: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: any
    environment:
      WP_HOST: mariadb:3306
      REDIS_HOST: redis:6379
    secrets:
      - maria_password
      - wp_user_password
      - wp_admin_password

  redis:
    build: ./requirements/redis/.
    image: requirements/redis
    deploy:
      restart_policy:
        condition: any
    networks:
      - inception
    volumes:
      - redis_data:/data
    environment:
      WP_HOST: mariadb:3306
      REDIS_PASSWORD: /run/secrets/redis_password
    secrets:
      - redis_password

  ftp:
    build: ./requirements/ftp/.
    image: requirements/ftp
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    deploy:
      restart_policy:
        condition: any
    secrets:
      - ftp_user_password


  nginx:
    build: ./requirements/nginx/.
    image: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: any

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/mariadb
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jyriarte/data/redis

networks:
  inception:
    driver: overlay
    attachable: true

secrets:
  maria_password:
    file: ../secrets/maria_password.txt
  maria_root_password:
    file: ../secrets/maria_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  redis_password:
    file: ../secrets/redis_password.txt
  ftp_user_password:
    file: ../secrets/ftp_user_password.txt
